before_install:
  - gem install cocoapods
install:
  - pod install
language: objective-c
osx_image: xcode12.2
xcode_workspace: Boozter/Boozter.xcworkspace
xcode_scheme: Boozter
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 8
script: 
 - xcodebuild test -workspace 'Boozter.xcworkspace' -scheme 'Boozter' -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 8'
